# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='like',
            field=models.BooleanField(default=True),
        ),
    ]
