# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_photo_photolikes_phototags_rsvp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhotoLikes',
            new_name='PhotoLike',
        ),
        migrations.RenameModel(
            old_name='PhotoTags',
            new_name='PhotoTag',
        ),
    ]
