# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 22:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20170706_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phototag',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='phototag',
            name='user',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='tags',
        ),
        migrations.DeleteModel(
            name='PhotoTag',
        ),
    ]
