# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 22:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_auto_20170706_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='_photo_tags_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
