# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_photo_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, upload_to='archive/%Y-%m'),
        ),
    ]
